repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: pipenv run isort tinder test
        types: [python]

      - id: black
        name: black
        stages: [commit]
        language: system
        entry: pipenv run black tinder test
        types: [python]

      - id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: pipenv run flake8 tinder test
        types: [python]
        exclude: setup.py

      - id: mypy
        name: mypy
        stages: [commit]
        language: system
        entry: pipenv run mypy tinder test
        types: [python]
        pass_filenames: false

      - id: pytest-cov
        name: pytest
        stages: [commit]
        language: system
        entry: pipenv run pytest --cov --cov-fail-under=10
        types: [python]
        pass_filenames: false